# Generated by Django 4.2.3 on 2023-07-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_route_ends_route_starts"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
