name: Docker Image

on: [push]

env:
  IMAGE: "andrewgodwin/aeracode"
  IMAGE_TAG: ""
  GOOGLECLOUD_PROJECT: ${{ secrets.GOOGLECLOUD_PROJECT }}
  GOOGLECLOUD_EMAIL: ${{ secrets.GOOGLECLOUD_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLECLOUD_PROJECT }}
          service_account_key: ${{ secrets.GOOGLECLOUD_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: "Authenticate Docker"
        run: gcloud auth configure-docker -q

      # Calculate the image name
      - name: Calculate Docker image name
        run: echo "IMAGE_TAG=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      # Add version to the local settings file
      - name: Save version number
        run: echo "VERSION='`git rev-parse --short HEAD`'" >> aerasite/settings/local.py

      # Build the Docker image
      - name: Build
        run: |
          docker build -t gcr.io/"$GOOGLECLOUD_PROJECT"/"$IMAGE":"$IMAGE_TAG" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push gcr.io/$GOOGLECLOUD_PROJECT/$IMAGE:$IMAGE_TAG

      # Deploy to Google Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy aeracode --quiet --image gcr.io/$GOOGLECLOUD_PROJECT/$IMAGE:$IMAGE_TAG --platform managed --region us-central1 --project $GOOGLECLOUD_PROJECT
